const $=id=>document.getElementById(id);
const LOCAL={北京:[39.9042,116.4074,'北京 · 中国'],上海:[31.2304,121.4737,'上海 · 中国'],广州:[23.1291,113.2644,'广州 · 中国'],深圳:[22.5431,114.0579,'深圳 · 中国'],三亚:[18.2528,109.5119,'三亚 · 海南 · 中国'],乌鲁木齐:[43.8256,87.6168,'乌鲁木齐 · 新疆 · 中国']};
let env={};let selectedScene='';let demandManual={};let planManual=false;let selectedPlan='Standard';let packageManual={};
let status={weather:['ERA5 / Open-Meteo','最近1年温度、湿度、降雨、风、辐射、降雪','未查询','—'],elev:['Open-Meteo Elevation','海拔','未查询','—'],air:['CAMS Global','PM10、Dust、SO₂、Sea Salt Aerosol','未查询','—']};
function iso(d){return d.toISOString().slice(0,10)}
function avg(a){const v=(a||[]).filter(Number.isFinite);return v.length?v.reduce((s,x)=>s+x,0)/v.length:NaN}
function q(a,p){const v=(a||[]).filter(Number.isFinite).sort((a,b)=>a-b);return v.length?v[Math.floor((v.length-1)*p)]:NaN}
function count(a,f){return(a||[]).reduce((n,x,i)=>n+(f(x,i)?1:0),0)}
function setStatus(k,s,r){status[k][2]=s;status[k][3]=r;renderStatus()}
function renderStatus(){$('statusBody').innerHTML=Object.values(status).map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td class="${x[2]==='成功'?'ok':x[2]==='失败'?'bad':'wait'}">${x[2]}</td><td>${x[3]}</td></tr>`).join('')}
function updateMap(){const la=Number($('lat').value),lo=Number($('lon').value),dx=.8,dy=.5;$('map').src=`https://www.openstreetmap.org/export/embed.html?bbox=${lo-dx}%2C${la-dy}%2C${lo+dx}%2C${la+dy}&layer=mapnik&marker=${la}%2C${lo}`}
async function locate(name){name=String(name||'').trim();if(LOCAL[name])return{lat:LOCAL[name][0],lon:LOCAL[name][1],name:LOCAL[name][2]};const r=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(name)}&count=1&language=zh`);if(!r.ok)throw Error('地名解析失败 HTTP '+r.status);const j=await r.json();if(!j.results?.length)throw Error('未找到地名');const x=j.results[0];return{lat:x.latitude,lon:x.longitude,name:[x.name,x.admin1,x.country].filter(Boolean).join(' · ')}}
async function loadWeather(lat,lon){const end=new Date();end.setUTCDate(end.getUTCDate()-10);const start=new Date(end);start.setUTCFullYear(start.getUTCFullYear()-1);const vars='temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,wind_speed_10m,shortwave_radiation';const u=`https://archive-api.open-meteo.com/v1/archive?latitude=${lat}&longitude=${lon}&start_date=${iso(start)}&end_date=${iso(end)}&hourly=${vars}&wind_speed_unit=ms&timezone=UTC&models=era5`;const r=await fetch(u);if(!r.ok)throw Error('ERA5 HTTP '+r.status);const j=await r.json();if(j.error)throw Error(j.reason||'ERA5错误');return{h:j.hourly||{},start:iso(start),end:iso(end)}}
async function loadElev(lat,lon){const r=await fetch(`https://api.open-meteo.com/v1/elevation?latitude=${lat}&longitude=${lon}`);if(!r.ok)throw Error('海拔 HTTP '+r.status);const j=await r.json();return j.elevation?.[0]}
async function loadAir(lat,lon){const e=new Date();e.setUTCDate(e.getUTCDate()-1);const s=new Date(e);s.setUTCDate(s.getUTCDate()-89);const u=`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${lat}&longitude=${lon}&hourly=pm10,dust,sulphur_dioxide,sea_salt_aerosol&start_date=${iso(s)}&end_date=${iso(e)}&timezone=auto&domains=cams_global`;const r=await fetch(u);if(!r.ok)throw Error('CAMS HTTP '+r.status);const j=await r.json();if(j.error)throw Error(j.reason||'CAMS错误');return j.hourly||{}}
function derive(h,air,elev){const T=h.temperature_2m||[],RH=h.relative_humidity_2m||[],P=h.precipitation||[],Snow=h.snowfall||[],W=h.wind_speed_10m||[],Rad=h.shortwave_radiation||[];const factor=T.length?8760/T.length:1;env={t99:q(T,.99),tmin:Math.min(...T.filter(Number.isFinite)),rhAvg:avg(RH),rh90:count(RH,x=>x>=90)*factor,rainYear:(P.filter(Number.isFinite).reduce((a,b)=>a+b,0))*factor,rain1h:Math.max(...P.filter(Number.isFinite)),snowHours:count(Snow,x=>x>0)*factor,wind95:q(W,.95),rad95:q(Rad,.95),alt:Number(elev||0),pm10:avg(air.pm10||[]),dust:avg(air.dust||[]),so2:avg(air.sulphur_dioxide||[]),salt:avg(air.sea_salt_aerosol||[])};Object.keys(env).forEach(k=>{if(!Number.isFinite(env[k]))env[k]=0})}
function riskLevel(metric){const v=env[metric]||0;const rule={t99:[45,40],tmin:[-30,-20],rh90:[1000,300],rainYear:[1800,900],rain1h:[80,30],snowHours:[120,30],alt:[3000,1500],pm10:[150,45],dust:[150,50],so2:[20,5],salt:[20,5],wind95:[15,10],rad95:[800,600]}[metric];if(!rule)return 1;if(metric==='tmin')return v<=rule[0]?3:v<=rule[1]?2:1;return v>=rule[0]?3:v>=rule[1]?2:1}
function renderEnv(){const defs=[['P99最高气温','t99','℃','ERA5'],['极端最低气温','tmin','℃','ERA5'],['年均相对湿度','rhAvg','%','ERA5'],['RH>90%','rh90','h/y','ERA5'],['年降水量','rainYear','mm/y','ERA5'],['最大1h降水','rain1h','mm/h','ERA5'],['海拔','alt','m','DEM'],['PM10均值','pm10','μg/m³','CAMS'],['Dust均值','dust','μg/m³','CAMS'],['Sea Salt Aerosol','salt','μg/m³','CAMS'],['SO₂均值','so2','μg/m³','CAMS'],['年降雪小时','snowHours','h/y','ERA5'],['P95风速','wind95','m/s','ERA5'],['P95太阳辐射','rad95','W/m²','ERA5']];$('envGrid').innerHTML=defs.map(d=>{const r=riskLevel(d[1]),cl=r===3?'r-high':r===2?'r-mid':'r-low',v=(env[d[1]]||0);return `<div class="metric"><small>${d[0]}</small><b>${(Math.round(v*10)/10)} ${d[2]}</b><em class="${cl}">${r===3?'高':r===2?'中':'低'}风险 · ${d[3]}</em></div>`}).join('')}
function proximity(v,min,max){if(v>=min&&v<=max)return 1;const span=Math.max(1,max-min);const d=v<min?min-v:v-max;return Math.max(0,1-d/span)}
function sceneScores(){const e=env;const scores={};scores['常温内陆气候']=100*(.25*proximity(e.t99,-5,36)+.2*proximity(e.rhAvg,40,75)+.2*proximity(e.rainYear,300,1200)+.15*proximity(e.alt,0,1200)+.2*proximity(e.pm10,0,80));scores['热带雨林气候']=100*(.25*proximity(e.t99,30,40)+.3*proximity(e.rhAvg,75,100)+.25*proximity(e.rainYear,1600,4000)+.1*proximity(e.rain1h,30,180)+.1*proximity(e.alt,0,1000));scores['滨海盐雾气候']=100*(.35*proximity(e.salt,5,100)+.25*proximity(e.rhAvg,65,100)+.2*proximity(e.rainYear,700,2500)+.1*proximity(e.t99,20,42)+.1*proximity(e.alt,0,600));scores['沙戈荒气候']=100*(.25*proximity(e.t99,35,55)+.25*proximity(e.pm10,80,500)+.15*proximity(e.dust,50,500)+.2*proximity(e.rainYear,0,300)+.15*proximity(e.rhAvg,10,50));scores['高温环境']=100*(.55*proximity(e.t99,38,55)+.25*proximity(e.rad95,550,1000)+.2*proximity(e.rhAvg,10,70));scores['高原高寒气候']=100*(.45*proximity(e.alt,1500,6000)+.3*proximity(e.tmin,-45,-10)+.15*proximity(e.rad95,550,1000)+.1*proximity(e.rhAvg,20,70));scores['寒地暴雪气候']=100*(.5*proximity(e.tmin,-45,-15)+.4*proximity(e.snowHours,20,1000)+.1*proximity(e.rhAvg,40,90));scores['海洋气候']=100*(.4*proximity(e.salt,8,120)+.25*proximity(e.rhAvg,70,100)+.15*proximity(e.rainYear,700,3000)+.1*proximity(e.wind95,8,30)+.1*proximity(e.alt,0,300));scores['工矿腐蚀环境']=100*(.4*proximity(e.so2,3,80)+.3*proximity(e.pm10,50,300)+.2*proximity(e.dust,30,300)+.1*proximity(e.rhAvg,40,90));return Object.entries(scores).map(([name,score])=>({name,score:Math.max(0,Math.min(99,Math.round(score)))})).sort((a,b)=>b.score-a.score)}
function renderScenes(){const arr=sceneScores();if(!selectedScene)selectedScene=arr[0].name;$('sceneBadge').textContent=`主场景：${arr[0].name} ${arr[0].score}% · 次场景：${arr[1].name} ${arr[1].score}%`;$('sceneGrid').innerHTML=arr.map((s,i)=>{const d=scenarioData[s.name];return `<div class="scene ${i===0?'primary-scene':''} ${selectedScene===s.name?'selected-scene':''}" onclick="selectScene('${s.name}')"><span class="pill">${i===0?'主场景':i===1?'次场景':'匹配'}</span><h4>${s.name}</h4><p>${d.def}</p><p><b>关键特征：</b>${d.features}</p><p>匹配度 ${s.score}%</p><div class="scorebar"><i style="width:${s.score}%"></i></div></div>`}).join('');return arr}
window.selectScene=function(name){selectedScene=name;demandManual={};planManual=false;renderDecision()}
function evidenceFor(type){const e=env;const map={heat:`P99高温 ${e.t99.toFixed(1)}℃；P95辐射 ${e.rad95.toFixed(0)}W/m²`,humidity:`年均RH ${e.rhAvg.toFixed(1)}%；RH>90% ${e.rh90.toFixed(0)}h/y`,rain:`年降水 ${e.rainYear.toFixed(0)}mm；最大1h ${e.rain1h.toFixed(1)}mm/h`,dust:`PM10 ${e.pm10.toFixed(1)}μg/m³；Dust ${e.dust.toFixed(1)}μg/m³`,salt:`Sea Salt Aerosol ${e.salt.toFixed(1)}μg/m³；RH ${e.rhAvg.toFixed(1)}%`,mist:`RH>90% ${e.rh90.toFixed(0)}h/y；年均RH ${e.rhAvg.toFixed(1)}%`,altitude:`海拔 ${e.alt.toFixed(0)}m；极端低温 ${e.tmin.toFixed(1)}℃`,cold:`极端低温 ${e.tmin.toFixed(1)}℃；降雪 ${e.snowHours.toFixed(0)}h/y`,snow:`降雪 ${e.snowHours.toFixed(0)}h/y；极端低温 ${e.tmin.toFixed(1)}℃`,marine:`Sea Salt ${e.salt.toFixed(1)}μg/m³；RH ${e.rhAvg.toFixed(1)}%；P95风速 ${e.wind95.toFixed(1)}m/s`,industry:`SO₂ ${e.so2.toFixed(1)}μg/m³；PM10 ${e.pm10.toFixed(1)}μg/m³`,normal:`P99高温 ${e.t99.toFixed(1)}℃；年降水 ${e.rainYear.toFixed(0)}mm`};return map[type]||'结合项目环境体检参数'}
function renderDemands(){const d=scenarioData[selectedScene];if(!d)return;d.demands.forEach((x,i)=>{const key=selectedScene+'#'+i;if(!(key in demandManual))demandManual[key]=true});const selected=d.demands.filter((x,i)=>demandManual[selectedScene+'#'+i]);$('demandCount').textContent=selected.length+' 条核心诉求';$('demandGrid').innerHTML=d.demands.map((x,i)=>{const key=selectedScene+'#'+i;return `<label class="demand"><input type="checkbox" ${demandManual[key]?'checked':''} onchange="demandManual['${key}']=this.checked;renderRequirements();renderPackages();renderResult()"><span><b>${x[0]}</b><br>${x[1]}<span class="evidence">环境依据：${evidenceFor(x[2])}</span></span></label>`}).join('')}
function renderRequirements(){const d=scenarioData[selectedScene];if(!d){$('reqBody').innerHTML='';return}let rows=[];d.demands.forEach((x,i)=>{if(!demandManual[selectedScene+'#'+i])return;const reqs=d.reqs[x[2]]||[];reqs.forEach((r,j)=>{const verify=j===0?'按项目技术规范/设计计算校核':j===1?'专项试验或环境验证':'设计评审+验证';rows.push([x[0],evidenceFor(x[2]),r,verify])})});const uniq=[];const seen=new Set();for(const r of rows){const k=r[2];if(!seen.has(k)){seen.add(k);uniq.push(r)}}$('reqCount').textContent=uniq.length+' 条设计需求';$('reqBody').innerHTML=uniq.length?uniq.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join(''):`<tr><td colspan="4" class="empty">请至少勾选一条客户核心诉求。</td></tr>`}
function envRiskCode(){const keys=['t99','tmin','rh90','rainYear','rain1h','snowHours','alt','pm10','dust','so2','salt'];return Math.max(...keys.map(riskLevel))}
function recommendedPlan(){const envCode=envRiskCode();const machine=Number($('machineLevel').value);let importance=Math.max(Number($('maintain').value),Number($('loss').value),$('machineType').value==='海上'?3:$('machineType').value==='国际陆上'?2:1,Number($('stage').value)>=3?2:1);const code=Math.min(3,Math.max(envCode,machine,importance));return{code,name:['','Standard','Pro','Plus'][code],envCode,machine,importance}}
function renderPlans(){const r=recommendedPlan();if(!planManual)selectedPlan=r.name;$('planBadge').textContent=`系统推荐：${r.name}`;const d=scenarioData[selectedScene];$('planGrid').innerHTML=['Standard','Pro','Plus'].map(name=>`<div class="plan ${selectedPlan===name?'selected':''}"><span class="pill">${name===r.name?'系统推荐':'可选'}</span><h4>${name}</h4><ul>${(d.plans[name]||[]).map(x=>`<li>${x}</li>`).join('')}</ul><div class="plan-footer"><span>作为场景主方案</span><input type="radio" name="plan" ${selectedPlan===name?'checked':''} onchange="selectedPlan='${name}';planManual=true;renderPlans();renderPackages();renderResult()"></div></div>`).join('');$('planReason').innerHTML=`推荐逻辑：环境风险等级 <b>${r.envCode}/3</b>，机组配置基线 <b>${r.machine}/3</b>，重要度修正 <b>${r.importance}/3</b>，取最高等级 → <b>${r.name}</b>。当前主场景为 <b>${selectedScene}</b>，方案内容按该场景技术货架匹配。`}
function packageTrigger(p){const types=p[3];let s=0;for(const t of types){if(t==='heat')s=Math.max(s,riskLevel('t99'));if(t==='humidity')s=Math.max(s,riskLevel('rh90'));if(t==='rain')s=Math.max(s,riskLevel('rainYear'),riskLevel('rain1h'));if(t==='dust')s=Math.max(s,riskLevel('pm10'),riskLevel('dust'));if(t==='salt')s=Math.max(s,riskLevel('salt'));if(t==='mist')s=Math.max(s,riskLevel('rh90'));if(t==='altitude')s=Math.max(s,riskLevel('alt'));if(t==='cold')s=Math.max(s,riskLevel('tmin'));if(t==='snow')s=Math.max(s,riskLevel('snowHours'));if(t==='marine')s=Math.max(s,riskLevel('salt'),riskLevel('rh90'),riskLevel('rainYear'));if(t==='industry')s=Math.max(s,riskLevel('so2'),riskLevel('pm10'))}const d=scenarioData[selectedScene];if(d&&d.demands.some((x,i)=>demandManual[selectedScene+'#'+i]&&types.includes(x[2])))s=Math.max(s,2);if(p[0]==='海洋强化包'&&selectedScene==='海洋气候')s=3;if(p[0]==='工矿污染包'&&selectedScene==='工矿腐蚀环境')s=3;return s}
function renderPackages(){let n=0;$('packageGrid').innerHTML=packages.map((p,i)=>{const auto=packageTrigger(p);if(!(i in packageManual))packageManual[i]=auto>=2;const sel=packageManual[i];if(sel)n++;const txt=auto>=3?'强烈推荐':auto===2?'推荐':auto===1?'可选':'不触发',cl=auto>=3?'strong':auto===2?'auto':'';return `<div class="package ${sel?'selected':''}"><input type="checkbox" ${sel?'checked':''} onchange="packageManual[${i}]=this.checked;renderPackages();renderResult()"><span class="tag ${cl}">${txt}</span><h4>${p[0]}</h4><p><b>适用：</b>${p[1]}<br>${p[2]}</p><small>触发等级 ${auto}/3 · 可人工覆盖</small></div>`}).join('');$('pkgCount').textContent=n+' 个升级包'}
function renderResult(){const selected=packages.filter((p,i)=>packageManual[i]).map(p=>p[0]);$('resultTitle').textContent=$('projectName').value||'项目';$('resultChips').innerHTML=`<span>主场景：${selectedScene||'—'}</span><span>主方案：${selectedPlan}</span><span>升级包：${selected.length}项</span><span>统计周期：最近1年</span>`;$('resultText').innerHTML=`建议配置：<b>${selectedScene||'待识别'} · ${selectedPlan}</b>${selected.length?' + '+selected.join(' + '):''}。设计需求已按实际气象参数自动转换，后续可直接作为整机/子系统需求分解和项目技术澄清的输入。`}
function renderDecision(){renderEnv();renderScenes();renderDemands();renderRequirements();renderPlans();renderPackages();renderResult()}
async function assess(byPlace){$('locMsg').className='msg';$('locMsg').textContent='正在定位并读取最近1年项目环境数据…';let lat=Number($('lat').value),lon=Number($('lon').value);try{if(byPlace){const l=await locate($('place').value);lat=l.lat;lon=l.lon;$('lat').value=lat;$('lon').value=lon;$('place').value=l.name;$('locMsg').textContent=`已定位：${l.name} ｜ ${lat.toFixed(4)}, ${lon.toFixed(4)}。正在查询数据…`}updateMap();setStatus('weather','查询中','—');setStatus('elev','查询中','—');setStatus('air','查询中','—');const w=await loadWeather(lat,lon);setStatus('weather','成功',`${w.start} ~ ${w.end} · ${(w.h.temperature_2m||[]).length}小时`);const [er,ar]=await Promise.allSettled([loadElev(lat,lon),loadAir(lat,lon)]);let elev=0,air={};if(er.status==='fulfilled'){elev=er.value;setStatus('elev','成功',Math.round(elev)+' m')}else setStatus('elev','失败',er.reason?.message||'失败');if(ar.status==='fulfilled'){air=ar.value;setStatus('air','成功','PM10 / Dust / SO₂ / Sea Salt 已返回')}else setStatus('air','失败',ar.reason?.message||'失败');derive(w.h,air,elev);selectedScene='';demandManual={};planManual=false;packageManual={};renderDecision();$('locMsg').textContent=`项目环境分析完成：${w.start} ~ ${w.end}。已完成场景识别、客户诉求、设计需求、主方案和升级包推荐。`}catch(e){console.error(e);$('locMsg').className='msg error';$('locMsg').textContent='数据查询失败：'+(e.message||String(e))}}
$('topRun').onclick=()=>assess(false);$('placeRun').onclick=()=>assess(true);$('coordRun').onclick=()=>assess(false);$('lat').onchange=updateMap;$('lon').onchange=updateMap;$('machineLevel').onchange=()=>{if(Object.keys(env).length){planManual=false;renderPlans();renderResult()}};$('machineType').onchange=$('maintain').onchange=$('loss').onchange=$('stage').onchange=()=>{if(Object.keys(env).length){planManual=false;renderPlans();renderResult()}};$('projectName').oninput=renderResult;
updateMap();renderStatus();$('envGrid').innerHTML='<div class="empty">等待项目环境查询…</div>';$('sceneGrid').innerHTML='<div class="empty">完成项目环境查询后识别9种场景。</div>';$('demandGrid').innerHTML='<div class="empty">识别场景后生成客户核心诉求。</div>';$('reqBody').innerHTML='<tr><td colspan="4" class="empty">识别客户核心诉求后生成设计需求。</td></tr>';$('planGrid').innerHTML='<div class="empty">完成环境风险和场景识别后匹配主方案。</div>';$('packageGrid').innerHTML='<div class="empty">完成环境与客户诉求识别后推荐升级包。</div>';
