(function(){
const ADMIN_KEY='ea_v25_admin_config';
try{const cfg=JSON.parse(localStorage.getItem(ADMIN_KEY)||'null');if(cfg){if(cfg.scenarios)Object.entries(cfg.scenarios).forEach(([n,o])=>{const d=scenarioData[n];if(!d)return;if(Array.isArray(o.demands))d.demands=o.demands;if(o.reqs)d.reqs=o.reqs;if(o.plans)d.plans={...d.plans,...o.plans}});if(Array.isArray(cfg.packages)&&cfg.packages.length)packages.splice(0,packages.length,...cfg.packages)}}catch(e){console.warn('管理员配置读取失败',e)}

loadWeather=async function(lat,lon){
 const years=Number($('periodYears').value||1),end=new Date();end.setUTCDate(end.getUTCDate()-10);const start=new Date(end);start.setUTCFullYear(start.getUTCFullYear()-years);
 const vars='temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,wind_speed_10m,shortwave_radiation';
 const merged={temperature_2m:[],relative_humidity_2m:[],precipitation:[],rain:[],snowfall:[],wind_speed_10m:[],shortwave_radiation:[]};
 let cursor=new Date(start),chunks=[];while(cursor<=end){let ce=new Date(Date.UTC(cursor.getUTCFullYear(),11,31));if(ce>end)ce=new Date(end);chunks.push([new Date(cursor),ce]);cursor=new Date(Date.UTC(ce.getUTCFullYear()+1,0,1))}
 for(let i=0;i<chunks.length;i++){const [cs,ce]=chunks[i];$('locMsg').textContent=`正在读取最近${years}年气象数据：${iso(cs)} ~ ${iso(ce)}（${i+1}/${chunks.length}）…`;const u=`https://archive-api.open-meteo.com/v1/archive?latitude=${lat}&longitude=${lon}&start_date=${iso(cs)}&end_date=${iso(ce)}&hourly=${vars}&wind_speed_unit=ms&timezone=UTC&models=era5`;const r=await fetch(u);if(!r.ok)throw Error('ERA5 HTTP '+r.status);const j=await r.json();if(j.error)throw Error(j.reason||'ERA5错误');Object.keys(merged).forEach(k=>merged[k].push(...(j.hourly?.[k]||[])))}
 if(!merged.temperature_2m.length)throw Error('ERA5 未返回小时温度数据');return{h:merged,start:iso(start),end:iso(end),years}
};

recommendedPlan=function(){const envCode=envRiskCode(),machine=Number($('machineLevel').value),typeFloor=$('machineType').value==='海上'?3:$('machineType').value==='国际陆上'?2:1,target=Math.max(envCode,typeFloor),gap=Math.max(0,target-machine),code=gap>=2?3:gap===1?2:1;return{code,name:['','Standard','Pro','Plus'][code],envCode,machine,typeFloor,target,gap}};
renderPlans=function(){const r=recommendedPlan();if(!planManual)selectedPlan=r.name;$('planBadge').textContent=`系统推荐：${r.name}`;const d=scenarioData[selectedScene];$('planGrid').innerHTML=['Standard','Pro','Plus'].map(name=>`<div class="plan ${selectedPlan===name?'selected':''}"><span class="pill">${name===r.name?'系统推荐':'可选'}</span><h4>${name}</h4><ul>${(d.plans[name]||[]).map(x=>`<li>${x}</li>`).join('')}</ul><div class="plan-footer"><span>作为场景主方案</span><input type="radio" name="plan" ${selectedPlan===name?'checked':''} onchange="selectedPlan='${name}';planManual=true;renderPlans();renderPackages();renderGap();renderResult()"></div></div>`).join('');$('planReason').innerHTML=`推荐逻辑：环境风险 <b>${r.envCode}/3</b>，机组类型要求 <b>${r.typeFloor}/3</b>，目标能力 <b>${r.target}/3</b>；当前机组配置 <b>${r.machine}/3</b>，能力差 ${r.gap} 级 → 推荐 <b>${r.name}</b>。`};

renderScenes=function(){const arr=sceneScores();if(!selectedScene)selectedScene=arr[0].name;$('sceneBadge').textContent=`主场景：${arr[0].name} ${arr[0].score}% · 次场景：${arr[1].name} ${arr[1].score}%`;$('sceneGrid').innerHTML=arr.map((s,i)=>{const d=scenarioData[s.name],cl=s.score>=70?'score-high':s.score>=45?'score-mid':'score-low',bar=s.score>=70?'bar-high':s.score>=45?'bar-mid':'bar-low',txt=s.score>=70?'高匹配':s.score>=45?'中匹配':'低匹配';return `<div class="scene ${cl} ${i===0?'primary-scene':''} ${selectedScene===s.name?'selected-scene':''}" onclick="selectScene('${s.name}')"><span class="pill">${i===0?'主场景':i===1?'次场景':txt}</span><h4>${s.name}</h4><p>${d.def}</p><p><b>关键特征：</b>${d.features}</p><p>匹配度 <b>${s.score}%</b> · ${txt}</p><div class="scorebar"><i class="${bar}" style="width:${s.score}%"></i></div></div>`}).join('');return arr};

const GAP_DOMAINS=[['高温',['t99'],['heat']],['低温',['tmin'],['cold']],['高湿/凝露',['rh90'],['humidity','mist']],['强降雨',['rainYear','rain1h'],['rain']],['沙尘/粉尘',['pm10','dust'],['dust']],['盐雾/腐蚀',['salt'],['salt','marine']],['高海拔',['alt'],['altitude']],['暴雪/结冰',['snowHours'],['snow']],['工矿污染',['so2','pm10'],['industry']],['强太阳辐射',['rad95'],['heat']]];
window.renderGap=function(){if(!Object.keys(env).length){$('gapBody').innerHTML='<tr><td colspan="7" class="empty">完成项目环境分析后计算 Design Gap。</td></tr>';return}const machineBase=Math.max(0,Number($('machineLevel').value)-1),planAdd={Standard:0,Pro:1,Plus:2}[selectedPlan]||0;let maxRemain=0;$('gapBody').innerHTML=GAP_DOMAINS.map(([name,metrics,types])=>{const need=Math.max(...metrics.map(riskLevel)),covered=packages.map((p,i)=>({p,i})).filter(x=>packageManual[x.i]&&x.p[3].some(t=>types.includes(t))).map(x=>x.p[0]),pkgAdd=covered.length?2:0,supplied=Math.min(3,machineBase+planAdd+pkgAdd),remain=Math.max(0,need-supplied);maxRemain=Math.max(maxRemain,remain);const cls=remain>=2?'gap-high':remain===1?'gap-mid':'gap-low';return `<tr><td><b>${name}</b></td><td>${need}/3</td><td>${machineBase}/3</td><td>+${planAdd}</td><td>${covered.length?'+2 · '+covered.join('、'):'0 · —'}</td><td class="${cls}">${remain}/3</td><td class="${cls}">${remain>=2?'高风险':remain===1?'中风险':'低风险'}</td></tr>`}).join('');$('gapBadge').textContent='综合剩余风险：'+(maxRemain>=2?'高':maxRemain===1?'中':'低')};

const oldPackages=renderPackages;renderPackages=function(){oldPackages();document.querySelectorAll('#packageGrid input[type=checkbox]').forEach(el=>el.addEventListener('change',()=>setTimeout(renderGap,0)))};
renderResult=function(){const selected=packages.filter((p,i)=>packageManual[i]).map(p=>p[0]),years=Number($('periodYears').value||1);$('resultTitle').textContent=$('projectName').value||'项目';$('resultChips').innerHTML=`<span>主场景：${selectedScene||'—'}</span><span>主方案：${selectedPlan}</span><span>升级包：${selected.length}项</span><span>统计周期：最近${years}年</span><span>${$('gapBadge').textContent||'Design Gap待评价'}</span>`;$('resultText').innerHTML=`建议配置：<b>${selectedScene||'待识别'} · ${selectedPlan}</b>${selected.length?' + '+selected.join(' + '):''}。设计需求已按实际气象参数转换，并完成 Design Gap 剩余风险评价。`};
renderDecision=function(){renderEnv();renderScenes();renderDemands();renderRequirements();renderPlans();renderPackages();renderGap();renderResult()};

assess=async function(byPlace){const years=Number($('periodYears').value||1);status.weather[1]=`最近${years}年温度、湿度、降雨、风、辐射、降雪`;renderStatus();$('locMsg').className='msg';$('locMsg').textContent=`正在定位并读取最近${years}年项目环境数据…`;let lat=Number($('lat').value),lon=Number($('lon').value);try{if(byPlace){const l=await locate($('place').value);lat=l.lat;lon=l.lon;$('lat').value=lat;$('lon').value=lon;$('place').value=l.name;$('locMsg').textContent=`已定位：${l.name} ｜ ${lat.toFixed(4)}, ${lon.toFixed(4)}。正在查询数据…`}updateMap();setStatus('weather','查询中','—');setStatus('elev','查询中','—');setStatus('air','查询中','—');const w=await loadWeather(lat,lon);setStatus('weather','成功',`${w.start} ~ ${w.end} · ${(w.h.temperature_2m||[]).length}小时`);const [er,ar]=await Promise.allSettled([loadElev(lat,lon),loadAir(lat,lon)]);let elev=0,air={};if(er.status==='fulfilled'){elev=er.value;setStatus('elev','成功',Math.round(elev)+' m')}else setStatus('elev','失败',er.reason?.message||'失败');if(ar.status==='fulfilled'){air=ar.value;setStatus('air','成功','PM10 / Dust / SO₂ / Sea Salt 已返回')}else setStatus('air','失败',ar.reason?.message||'失败');derive(w.h,air,elev);selectedScene='';demandManual={};planManual=false;packageManual={};renderDecision();$('locMsg').textContent=`项目环境分析完成：${w.start} ~ ${w.end}（最近${years}年）。已完成场景、诉求、设计需求、主方案、升级包和 Design Gap。`}catch(e){console.error(e);$('locMsg').className='msg error';$('locMsg').textContent='数据查询失败：'+(e.message||String(e))}};

$('topRun').onclick=()=>assess(false);$('placeRun').onclick=()=>assess(true);$('coordRun').onclick=()=>assess(false);
$('machineLevel').onchange=()=>{if(Object.keys(env).length){planManual=false;renderPlans();renderPackages();renderGap();renderResult()}};
$('machineType').onchange=()=>{if(Object.keys(env).length){planManual=false;renderPlans();renderPackages();renderGap();renderResult()}};
$('periodYears').onchange=()=>{const y=Number($('periodYears').value);status.weather[1]=`最近${y}年温度、湿度、降雨、风、辐射、降雪`;renderStatus();$('locMsg').textContent=`气象统计周期已切换为最近${y}年，请重新查询项目环境。`};
$('gapBody').innerHTML='<tr><td colspan="7" class="empty">完成项目环境分析后计算 Design Gap。</td></tr>';
})();