import {number,delay,checkAbort} from './data-quality.js';
import {alignSeries,requestJson,SourceError} from './sources-v332.js';
export * from './sources-v332.js';

export const CAMS_SEA_SALT_AUTO_URL='https://global-marine-corrosion-direct-v332.vercel.app/api/salt';
function configuredUrl(explicit){if(explicit)return explicit;try{const s=globalThis.localStorage?.getItem('marineCamsSeaSaltUrl');if(s)return s}catch{}return globalThis.__MARINE_CAMS_SEA_SALT_URL__||CAMS_SEA_SALT_AUTO_URL}
function metadata(data,type,handling){return {type,source:data.source||'CAMS sea salt Auto',dataset:data.dataset,modelLevel:data.modelLevel,grid:data.grid||null,resolution:data.resolution,retrievedAt:data.retrievedAt,referenceRhPercent:80,massBasis:data.massBasis||'CAMS sea-salt mass/radii at RH80',autoSeaSalt:true,temporalHandling:handling}}
function monthlyToHourly(data,baseTimes){const maps=[new Map(),new Map(),new Map()];for(let i=0;i<(data.time||[]).length;i++){const d=new Date(data.time[i]);if(!Number.isFinite(d.getTime()))continue;for(let j=0;j<3;j++){const v=number(data['ss'+(j+1)]?.[i]);if(v!==null)maps[j].set(d.getUTCMonth()+1,v)}}const out={time:[...baseTimes],flags:{},fieldMeta:{}};for(let j=0;j<3;j++){const k='ss'+(j+1);out[k]=baseTimes.map(t=>{const d=new Date(t);return Number.isFinite(d.getTime())?maps[j].get(d.getUTCMonth()+1)??null:null});out.flags[k]=out[k].map(v=>v===null?'MISSING':'DATA');out.fieldMeta[k]={source:'CAMS EAC4 monthly reanalysis',unit:'kg/kg',originalUnit:data.units?.upstream?.[k]||'kg kg**-1',unitBasis:'ADS API / lowest model level 60 / RH80 basis',resolution:data.resolution||'0.75° monthly mean',referenceRhPercent:80,massBasis:'wet sea-salt mass at RH80; science kernel converts /4.3 to dry salt',temporalHandling:'monthly mean expanded to each UTC hour of same month'}}out.provenance=metadata(data,'DATA/REANALYSIS','monthly mean expanded to each UTC hour');return out}
function forecastToHourly(data,baseTimes){const raw={time:data.time||[],ss1:(data.ss1||[]).map(number),ss2:(data.ss2||[]).map(number),ss3:(data.ss3||[]).map(number)};const a=alignSeries(baseTimes,raw,['ss1','ss2','ss3'],{maxGapHours:6});a.fieldMeta=Object.fromEntries(['ss1','ss2','ss3'].map(k=>[k,{source:'CAMS Global atmospheric composition forecast',unit:'kg/kg',originalUnit:data.units?.upstream?.[k]||'kg kg**-1',unitBasis:'ADS API / lowest model level 137 / RH80 basis',resolution:data.resolution||'~0.4° / 3 h',referenceRhPercent:80,massBasis:'wet sea-salt mass at RH80; science kernel converts /4.3 to dry salt',temporalHandling:'3 h forecast aligned to hourly within bounded gaps'}]));a.provenance=metadata(data,'DATA/FORECAST','3 h forecast aligned hourly');return a}
export async function fetchCamsSeaSaltAuto({lat,lon,mode,year,baseTimes,signal,url,onProgress=()=>{},resumeJob=null}={}){if(!Number.isFinite(Number(lat))||!Number.isFinite(Number(lon))||!['historical','current'].includes(mode)||!Array.isArray(baseTimes)||!baseTimes.length)throw new SourceError('INPUT','CAMS Sea Salt Auto 输入无效');const endpoint=configuredUrl(url),payload={lat:Number(lat),lon:Number(lon),mode,...(mode==='historical'?{year:Number(year)}:{})};let response=await requestJson(resumeJob?`${endpoint}?job=${encodeURIComponent(resumeJob)}`:endpoint,{method:resumeJob?'GET':'POST',...(!resumeJob?{headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{}),signal,timeout:30000,retries:0});const started=Date.now();while(response.status===202||['accepted','queued','running'].includes(String(response.data?.status||'').toLowerCase())){checkAbort(signal);const job=String(response.data?.jobId||'');if(!/^[A-Za-z0-9_-]{8,4096}$/.test(job))throw new SourceError('INVALID_RESPONSE','CAMS海盐任务缺少有效编号');onProgress({status:response.data?.status||'running',jobId:job,cycle:response.data?.cycle||null,detail:'CAMS ADS正在准备海盐三粒径数据'});if(Date.now()-started>300000){const e=new SourceError('PENDING','CAMS海盐任务仍在准备，可重试继续');e.jobId=job;throw e}await delay(Math.max(2000,Math.min(10000,Number(response.data?.retryAfterSeconds||5)*1000)),signal);response=await requestJson(`${endpoint}?job=${encodeURIComponent(job)}`,{signal,timeout:30000,retries:0})}const data=response.data;if(!data?.configured)throw new SourceError('NOT_CONFIGURED',data?.error?.message||'CAMS海盐Auto服务未配置');if(!Array.isArray(data.time)||!data.time.length)throw new SourceError('INVALID_RESPONSE','CAMS海盐Auto未返回时间轴');for(const k of ['ss1','ss2','ss3'])if(!Array.isArray(data[k])||data[k].length!==data.time.length)throw new SourceError('INVALID_RESPONSE',`CAMS海盐Auto缺少${k}`);return mode==='historical'?monthlyToHourly(data,baseTimes):forecastToHourly(data,baseTimes)}
export function mergeAutoSeaSalt(cams,salt){if(!salt?.time?.length)return cams;const n=salt.time.length,base=cams&&cams.time?.length===n?cams:{time:[...salt.time],flags:{},fieldMeta:{},provenance:{type:'MISSING',source:'CAMS base missing'}};const out={...base,time:[...salt.time],flags:{...(base.flags||{})},fieldMeta:{...(base.fieldMeta||{})},sourceByIndex:{...(base.sourceByIndex||{})},provenance:{...(base.provenance||{}),type:'MIXED',seaSalt:salt.provenance}};for(const k of ['ss1','ss2','ss3']){out[k]=[...(salt[k]||Array(n).fill(null))];out.flags[k]=[...(salt.flags?.[k]||Array(n).fill('MISSING'))];out.fieldMeta[k]={...(salt.fieldMeta?.[k]||{})};out.sourceByIndex[k]=out[k].map(v=>number(v)===null?'MISSING':salt.provenance?.source||'CAMS Sea Salt Auto')}out.provenance.source=[base.provenance?.source,salt.provenance?.source].filter(Boolean).join(' + ');out.autoSeaSalt=salt.provenance;return out}
