import {number,delay,checkAbort} from './data-quality.js';
import {alignSeries,requestJson,SourceError} from './sources-v332.js';
export * from './sources-v332.js';

export const CAMS_SEA_SALT_AUTO_URL='https://global-marine-corrosion-direct-v332.vercel.app/api/salt';
export const CAMS_SEA_SALT_FLUX_URL='https://global-marine-corrosion-direct-v332.vercel.app/api/salt_flux';
export const CAMS_FLUX_FIELDS=['ssDry1','ssDry2','ssDry3','ssSed1','ssSed2','ssSed3','ssWetConv1','ssWetConv2','ssWetConv3','ssWetLs1','ssWetLs2','ssWetLs3'];

function configuredUrl(explicit,key,globalKey,fallback){if(explicit)return explicit;try{const s=globalThis.localStorage?.getItem(key);if(s)return s}catch{}return globalThis[globalKey]||fallback}
function metadata(data,type,handling){return {type,source:data.source||'CAMS sea salt Auto',dataset:data.dataset,modelLevel:data.modelLevel,grid:data.grid||null,resolution:data.resolution,retrievedAt:data.retrievedAt,referenceRhPercent:80,massBasis:data.massBasis||'CAMS sea-salt mass/radii at RH80',autoSeaSalt:true,temporalHandling:handling}}
function monthlyToHourly(data,baseTimes){const maps=[new Map(),new Map(),new Map()];for(let i=0;i<(data.time||[]).length;i++){const d=new Date(data.time[i]);if(!Number.isFinite(d.getTime()))continue;for(let j=0;j<3;j++){const v=number(data['ss'+(j+1)]?.[i]);if(v!==null)maps[j].set(d.getUTCMonth()+1,v)}}const out={time:[...baseTimes],flags:{},fieldMeta:{}};for(let j=0;j<3;j++){const k='ss'+(j+1);out[k]=baseTimes.map(t=>{const d=new Date(t);return Number.isFinite(d.getTime())?maps[j].get(d.getUTCMonth()+1)??null:null});out.flags[k]=out[k].map(v=>v===null?'MISSING':'DATA');out.fieldMeta[k]={source:'CAMS EAC4 monthly reanalysis',unit:'kg/kg',originalUnit:data.units?.upstream?.[k]||'kg kg**-1',unitBasis:'ADS API / lowest model level 60 / RH80 basis',resolution:data.resolution||'0.75° monthly mean',referenceRhPercent:80,massBasis:'wet sea-salt mass at RH80; science kernel converts /4.3 to dry salt',temporalHandling:'monthly mean expanded to each UTC hour of same month'}}out.provenance=metadata(data,'DATA/REANALYSIS','monthly mean expanded to each UTC hour');return out}
function forecastToHourly(data,baseTimes){const raw={time:data.time||[],ss1:(data.ss1||[]).map(number),ss2:(data.ss2||[]).map(number),ss3:(data.ss3||[]).map(number)};const a=alignSeries(baseTimes,raw,['ss1','ss2','ss3'],{maxGapHours:6});a.fieldMeta=Object.fromEntries(['ss1','ss2','ss3'].map(k=>[k,{source:'CAMS Global atmospheric composition forecast',unit:'kg/kg',originalUnit:data.units?.upstream?.[k]||'kg kg**-1',unitBasis:'ADS API / lowest model level 137 / RH80 basis',resolution:data.resolution||'~0.4° / 3 h',referenceRhPercent:80,massBasis:'wet sea-salt mass at RH80; science kernel converts /4.3 to dry salt',temporalHandling:'3 h forecast aligned to hourly within bounded gaps'}]));a.provenance=metadata(data,'DATA/FORECAST','3 h forecast aligned hourly');return a}

async function pollAdsEndpoint({endpoint,payload,signal,onProgress,resumeJob,detail,pendingMessage,maxWaitMs=300000}){let response=await requestJson(resumeJob?`${endpoint}?job=${encodeURIComponent(resumeJob)}`:endpoint,{method:resumeJob?'GET':'POST',...(!resumeJob?{headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{}),signal,timeout:30000,retries:0});const started=Date.now();while(response.status===202||['accepted','queued','running'].includes(String(response.data?.status||'').toLowerCase())){checkAbort(signal);const job=String(response.data?.jobId||'');if(!/^[A-Za-z0-9_-]{8,4096}$/.test(job))throw new SourceError('INVALID_RESPONSE','CAMS任务缺少有效编号');onProgress({status:response.data?.status||'running',jobId:job,cycle:response.data?.cycle||null,chunk:response.data?.chunk||null,detail});if(Date.now()-started>maxWaitMs){const e=new SourceError('PENDING',pendingMessage);e.jobId=job;e.chunk=response.data?.chunk||null;throw e}await delay(Math.max(2000,Math.min(10000,Number(response.data?.retryAfterSeconds||5)*1000)),signal);response=await requestJson(`${endpoint}?job=${encodeURIComponent(job)}`,{signal,timeout:30000,retries:0})}return response.data}

export async function fetchCamsSeaSaltAuto({lat,lon,mode,year,baseTimes,signal,url,onProgress=()=>{},resumeJob=null}={}){if(!Number.isFinite(Number(lat))||!Number.isFinite(Number(lon))||!['historical','current'].includes(mode)||!Array.isArray(baseTimes)||!baseTimes.length)throw new SourceError('INPUT','CAMS Sea Salt Auto 输入无效');const endpoint=configuredUrl(url,'marineCamsSeaSaltUrl','__MARINE_CAMS_SEA_SALT_URL__',CAMS_SEA_SALT_AUTO_URL),payload={lat:Number(lat),lon:Number(lon),mode,...(mode==='historical'?{year:Number(year)}:{})};const data=await pollAdsEndpoint({endpoint,payload,signal,onProgress,resumeJob,detail:'CAMS ADS正在准备海盐三粒径数据',pendingMessage:'CAMS海盐任务仍在准备，可重试继续'});if(!data?.configured)throw new SourceError('NOT_CONFIGURED',data?.error?.message||'CAMS海盐Auto服务未配置');if(!Array.isArray(data.time)||!data.time.length)throw new SourceError('INVALID_RESPONSE','CAMS海盐Auto未返回时间轴');for(const k of ['ss1','ss2','ss3'])if(!Array.isArray(data[k])||data[k].length!==data.time.length)throw new SourceError('INVALID_RESPONSE',`CAMS海盐Auto缺少${k}`);return mode==='historical'?monthlyToHourly(data,baseTimes):forecastToHourly(data,baseTimes)}

function validateFluxData(data){if(!data?.configured)throw new SourceError('NOT_CONFIGURED',data?.error?.message||'CAMS海盐沉降通量服务未配置');if(!Array.isArray(data.time)||!data.time.length)throw new SourceError('INVALID_RESPONSE','CAMS海盐沉降通量未返回时间轴');for(const k of CAMS_FLUX_FIELDS)if(!Array.isArray(data[k])||data[k].length!==data.time.length)throw new SourceError('INVALID_RESPONSE',`CAMS海盐沉降通量缺少${k}`);return data}
function combineFluxChunks(parts){const ordered=[...parts].sort((a,b)=>Number(a.chunk||0)-Number(b.chunk||0));if(ordered.length!==4)throw new SourceError('INVALID_RESPONSE',`CAMS历史海盐沉降通量仅返回${ordered.length}/4个季度`);const first=ordered[0],out={...first,time:[],coverage:{},chunks:ordered.map(x=>({chunk:x.chunk,chunkRange:x.chunkRange,samples:x.time?.length||0,retrievedAt:x.retrievedAt}))};for(const k of CAMS_FLUX_FIELDS)out[k]=[];for(const p of ordered){out.time.push(...p.time);for(const k of CAMS_FLUX_FIELDS)out[k].push(...p[k])}const order=[...out.time.keys()].sort((a,b)=>String(out.time[a]).localeCompare(String(out.time[b]))),seen=new Set(),keep=[];for(const i of order){const t=String(out.time[i]);if(!seen.has(t)){seen.add(t);keep.push(i)}}out.time=keep.map(i=>out.time[i]);for(const k of CAMS_FLUX_FIELDS){out[k]=keep.map(i=>out[k][i]);out.coverage[k]=out[k].filter(v=>number(v)!==null).length/Math.max(1,out[k].length)}out.source='CAMS archived operational sea-salt deposition flux (4-quarter aggregate)';out.productType='ARCHIVED_FORECAST_FLUX';out.retrievedAt=ordered.map(x=>x.retrievedAt).filter(Boolean).sort().at(-1)||first.retrievedAt;return out}
function fluxToHourly(data,baseTimes,mode){const raw={time:data.time||[]};for(const k of CAMS_FLUX_FIELDS)raw[k]=(data[k]||[]).map(number);const a=alignSeries(baseTimes,raw,CAMS_FLUX_FIELDS,{maxGapHours:4});a.fieldMeta=Object.fromEntries(CAMS_FLUX_FIELDS.map(k=>[k,{source:data.source||'CAMS sea-salt deposition flux',unit:'kg/(m²·s)',originalUnit:data.units?.upstream?.[k]||'kg m**-2 s**-1',unitBasis:'ADS API surface deposition flux',resolution:data.resolution||'~0.4° / 3 h',massBasis:data.massBasis||'CAMS sea-salt prognostic mass; downstream converts /4.3 to dry salt',temporalHandling:'3 h CAMS flux aligned to platform hourly axis within 4 h bounded gap'}]));a.provenance={type:mode==='historical'?'DATA/ARCHIVED_FORECAST_FLUX':'DATA/FORECAST_FLUX',source:data.source,dataset:data.dataset,productType:data.productType,grid:data.grid||null,resolution:data.resolution,retrievedAt:data.retrievedAt,massBasis:data.massBasis,autoSeaSaltFlux:true,chunks:data.chunks||null,temporalHandling:mode==='historical'?'four quarterly archived forecast chunks aggregated, then 3 h flux aligned hourly':'3 h deposition flux aligned hourly'};return a}
export async function fetchCamsSeaSaltFluxAuto({lat,lon,mode,year,baseTimes,signal,url,onProgress=()=>{},resumeJob=null}={}){if(!Number.isFinite(Number(lat))||!Number.isFinite(Number(lon))||!['historical','current'].includes(mode)||!Array.isArray(baseTimes)||!baseTimes.length)throw new SourceError('INPUT','CAMS Sea Salt Flux 输入无效');if(mode==='historical'&&Number(year)<2019)throw new SourceError('DATA_UNAVAILABLE','CAMS归档海盐沉降通量完整年度从2019起用于本平台');const endpoint=configuredUrl(url,'marineCamsSeaSaltFluxUrl','__MARINE_CAMS_SEA_SALT_FLUX_URL__',CAMS_SEA_SALT_FLUX_URL),basePayload={lat:Number(lat),lon:Number(lon),mode,...(mode==='historical'?{year:Number(year)}:{})};if(mode==='current'){const data=validateFluxData(await pollAdsEndpoint({endpoint,payload:basePayload,signal,onProgress,resumeJob,detail:'CAMS ADS正在准备海盐 dry/sedimentation/wet deposition 通量',pendingMessage:'CAMS海盐沉降通量任务仍在准备，可重试继续',maxWaitMs:300000}));return fluxToHourly(data,baseTimes,mode)}const parts=new Map();if(resumeJob){const resumed=validateFluxData(await pollAdsEndpoint({endpoint,payload:basePayload,signal,onProgress,resumeJob,detail:'继续CAMS历史海盐沉降通量季度任务',pendingMessage:'CAMS历史海盐沉降通量季度任务仍在准备，可重试继续',maxWaitMs:600000}));const chunk=Number(resumed.chunk);if(chunk>=1&&chunk<=4)parts.set(chunk,resumed)}for(let chunk=1;chunk<=4;chunk++){if(parts.has(chunk))continue;checkAbort(signal);onProgress({stage:'cams-sea-salt-flux',chunk,detail:`CAMS历史沉降通量：提交第${chunk}/4季度`});const data=validateFluxData(await pollAdsEndpoint({endpoint,payload:{...basePayload,chunk},signal,onProgress,resumeJob:null,detail:`CAMS历史沉降通量：第${chunk}/4季度处理中`,pendingMessage:`CAMS历史沉降通量第${chunk}/4季度仍在准备，可重试继续`,maxWaitMs:600000}));if(Number(data.chunk)!==chunk)throw new SourceError('INVALID_RESPONSE',`CAMS历史沉降通量季度编号不一致：期望${chunk}，返回${data.chunk}`);parts.set(chunk,data)}return fluxToHourly(combineFluxChunks([...parts.values()]),baseTimes,mode)}

export function mergeAutoSeaSalt(cams,salt){if(!salt?.time?.length)return cams;const n=salt.time.length,base=cams&&cams.time?.length===n?cams:{time:[...salt.time],flags:{},fieldMeta:{},provenance:{type:'MISSING',source:'CAMS base missing'}};const out={...base,time:[...salt.time],flags:{...(base.flags||{})},fieldMeta:{...(base.fieldMeta||{})},sourceByIndex:{...(base.sourceByIndex||{})},provenance:{...(base.provenance||{}),type:'MIXED',seaSalt:salt.provenance}};for(const k of ['ss1','ss2','ss3']){out[k]=[...(salt[k]||Array(n).fill(null))];out.flags[k]=[...(salt.flags?.[k]||Array(n).fill('MISSING'))];out.fieldMeta[k]={...(salt.fieldMeta?.[k]||{})};out.sourceByIndex[k]=out[k].map(v=>number(v)===null?'MISSING':salt.provenance?.source||'CAMS Sea Salt Auto')}out.provenance.source=[base.provenance?.source,salt.provenance?.source].filter(Boolean).join(' + ');out.autoSeaSalt=salt.provenance;return out}
export function mergeAutoSeaSaltFlux(cams,flux){if(!flux?.time?.length)return cams;const n=flux.time.length,base=cams&&cams.time?.length===n?cams:{time:[...flux.time],flags:{},fieldMeta:{},provenance:{type:'MISSING',source:'CAMS base missing'}};const out={...base,time:[...flux.time],flags:{...(base.flags||{})},fieldMeta:{...(base.fieldMeta||{})},sourceByIndex:{...(base.sourceByIndex||{})},provenance:{...(base.provenance||{}),type:'MIXED',seaSaltFlux:flux.provenance}};for(const k of CAMS_FLUX_FIELDS){out[k]=[...(flux[k]||Array(n).fill(null))];out.flags[k]=[...(flux.flags?.[k]||Array(n).fill('MISSING'))];out.fieldMeta[k]={...(flux.fieldMeta?.[k]||{})};out.sourceByIndex[k]=out[k].map(v=>number(v)===null?'MISSING':flux.provenance?.source||'CAMS Sea Salt Flux')}out.provenance.source=[base.provenance?.source,flux.provenance?.source].filter(Boolean).join(' + ');out.autoSeaSaltFlux=flux.provenance;return out}
